### ISSUE TITLE
Error building llvm and static libclang

### ISSUE THREAD

**Issue by JosephBoyd** [borodust/libresect#4]
Get the following when running ./build_clang.sh on ubuntu 12.04

...
-- Up-to-date: /home/joe/cl/libresect/llvm-bin/lib/libLLVMWindowsManifest.a
-- Installing: /usr/lib/ocaml/llvm/llvm.mli
CMake Error at bindings/ocaml/llvm/cmake_install.cmake:54 (file):
  file INSTALL cannot copy file
  "/home/joe/cl/libresect/build/llvm/bindings/ocaml/llvm/llvm.mli" to
  "/usr/lib/ocaml/llvm/llvm.mli": Permission denied.
Call Stack (most recent call first):
  bindings/ocaml/cmake_install.cmake:47 (include)
  cmake_install.cmake:76 (include)

gmake: *** [Makefile:125: install] Error 1
-- Downloading ncurses sources, prebuilt z3 & prebuilt libclang with sources; this is ~500MB, please be patient, 'libclang_prebuilt' will take several minutes ...
-- * Downloading ncurses_sources from https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.2.tar.gz
-- * Downloading z3_prebuilt from https://github.com/Z3Prover/z3/releases/download/z3-4.8.7/z3-4.8.7-x64-ubuntu-16.04.zip
CMake Error at cmake/modules/LinuxMacosBuild.cmake:46 (include):
  include could not find load file:

    HandleLLVMOptions
Call Stack (most recent call first):
  CMakeLists.txt:13 (include)

CMake Error at cmake/modules/LinuxMacosBuild.cmake:47 (include):
  include could not find load file:

    AddLLVM
Call Stack (most recent call first):
  CMakeLists.txt:13 (include)

CMake Error at /home/joe/cl/libresect/llvm/clang/cmake/modules/AddClang.cmake:1 (include):
  include could not find load file:

    LLVMDistributionSupport
Call Stack (most recent call first):
  cmake/modules/LinuxMacosBuild.cmake:48 (include)
  CMakeLists.txt:13 (include)

CMake Error at /home/joe/cl/libresect/llvm/clang/cmake/modules/AddClang.cmake:105 (llvm_add_library):
  Unknown CMake command "llvm_add_library".
Call Stack (most recent call first):
  cmake/modules/LinuxMacosBuild.cmake:81 (add_clang_library)
  CMakeLists.txt:13 (include)

-- Configuring incomplete, errors occurred!
See also "/home/joe/cl/libresect/build/libclang-static/CMakeFiles/CMakeOutput.log".

**Comment by borodust** [comment]
12.04 is super old - I don't have one around so I can't debug that particular problem on my machine.

It's strange that it is trying to install into `/usr/lib/`. Maybe `cmake` is too old? Try building LLVM manually using snippet from `build_clang.sh` (setting all variables by hand):
```sh
cmake -DCMAKE_INSTALL_PREFIX=$LLVM_INSTALL_DIR \
      -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
      -DLLVM_USE_LINKER=gold \
      -DLLVM_ENABLE_PROJECTS="clang;" \
      -DLLVM_TARGETS_TO_BUILD='X86;AArch64;' \
      -DLIBCLANG_BUILD_STATIC=ON \
      -DBUILD_SHARED_LIBS=OFF \
      $LLVM_DIR \
    && cmake --build $BUILD_DIR --target install --config "$BUILD_TYPE" --parallel $BUILD_THREAD_COUNT
```

**Comment by JosephBoyd** [comment]
Sorry transposed numbers, actually on 21.04 ubuntu. Thanks for the recommendation. I added the following to cmake command in build_clang.sh and ran it successfully.

-DLLVM_ENABLE_BINDINGS=OFF

**Comment by borodust** [comment]
Thanks! I'll add it to the script.
